[tool.poetry]
name = "pypahe"
version = "1.0.0"
description = "pypahe is a PYthon PAckage HElper command-line tool"
license = "GPL-3.0-only"
authors = ["Antoine <achatain@users.noreply.github.com>"]
homepage = "https://bonjour.software"
repository = "https://github.com/bonjoursoftware/pypahe"
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
requests = "2.34.2"

[tool.poetry.group.dev.dependencies]
black = "26.10.0"
flake8 = "7.4.1"
httpretty = "1.1.4"
mypy = "2.4.0"
pytest = "9.1.1"
pytest-cov = "7.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
